# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='spotifyId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
