# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-24 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_spotifyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='youtubeId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
