# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_youtubeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordListens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_key', models.CharField(blank=True, max_length=64, null=True)),
                ('listen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Listen')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='spotifyId',
        ),
        migrations.RemoveField(
            model_name='record',
            name='youtubeId',
        ),
        migrations.AddField(
            model_name='recordlistens',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
        migrations.AddField(
            model_name='record',
            name='listens',
            field=models.ManyToManyField(through='records.RecordListens', to='records.Listen'),
        ),
    ]
