# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20190326_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
