# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20190326_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordlistens',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
