# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_recordlistens_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
