# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20191028_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='master',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
