# Generated by Django 3.2.4 on 2022-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_artist_collectionupdated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecords',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
