# Generated by Django 3.2.10 on 2022-01-18 17:03

from django.db import migrations, models
from django.db.models.functions import Substr, Lower


def set_init_sname(apps, schema_editor):
    Artist = apps.get_model('records', 'Artist')
    Artist.objects.all().update(sname=Lower(Substr('name', 1, 20)))


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20220114_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='sname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(
                fields=['sname'], name='records_art_sname_8fb61c_idx'),
        ),
        migrations.RunPython(
            set_init_sname, reverse_code=migrations.RunPython.noop, atomic=True),
    ]
