# Generated by Django 3.2.10 on 2022-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20220118_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to='records/covers'),
        ),
    ]
