# Generated by Django 3.2.20 on 2023-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_record_cover_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to='records'),
        ),
    ]
