# Generated by Django 3.2.20 on 2023-12-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_record_cover_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='genres',
            field=models.ManyToManyField(to='records.Genre'),
        ),
    ]
