# Generated by Django 4.2.8 on 2024-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20231227_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listen',
            name='template',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
