# Generated by Django 4.2.8 on 2024-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_alter_artist_name_alter_listen_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordartists',
            name='anv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
