# Generated by Django 4.2.8 on 2024-02-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_recordartists_anv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='collectionUpdated',
            new_name='collection_updated',
        ),
    ]
