# Generated by Django 4.2.8 on 2024-02-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_rename_collectionupdated_artist_collection_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='release_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
